// LOGIN CONSTANT
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

//REGISTER CONSTANT
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

//LOAD USER
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';

//ALL USERS
export const ALL_USER_SUCCESS = 'ALL_USER_SUCCESS';
